# Generated by Django 5.0.4 on 2024-04-08 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(db_index=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('male', 'мужской'), ('female', 'женский')], max_length=255, verbose_name='пол')),
            ],
        ),
        migrations.CreateModel(
            name='SportClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название спортивного клуба')),
                ('address', models.TextField(help_text='ул. Березовая, д.5', verbose_name='Адрес спортивного клуба')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(db_index=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('male', 'мужской'), ('female', 'женский')], max_length=255, verbose_name='пол')),
                ('kind_of_training', models.CharField(help_text='Тренер по боксу', max_length=255, verbose_name='Вид деятельности')),
                ('sport_clubs', models.ManyToManyField(blank=True, related_name='club_coaches', to='schedule_api.sportclub', verbose_name='Спортивные клубы')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField(db_index=True)),
                ('training_time', models.TimeField(db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='schedule_api.client', verbose_name='Клиент')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='schedule_api.sportclub', verbose_name='Спортивный клуб')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='schedule_api.coach', verbose_name='Тренер')),
            ],
        ),
    ]
