# Generated by Django 5.0.4 on 2024-04-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='training_time',
        ),
        migrations.AddField(
            model_name='training',
            name='start_time',
            field=models.TimeField(db_index=True, default='11:11:11', verbose_name='Время начала занятия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='stop_time',
            field=models.TimeField(db_index=True, default='11:11:11', verbose_name='Время окончания занятия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training',
            name='training_date',
            field=models.DateField(db_index=True, verbose_name='Запланированная дата тренировки'),
        ),
    ]
